config/routes.rb
Rails.application.routes.draw do
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'
  root to: 'pages#home'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end
  
  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
    # redirect_to root_path, notice: 'Article détruit'
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wonderlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%#= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#=javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mr-4">
  <h1>Welcome to your Wonderlist</h1>
  <h2><%= link_to 'See my tasks', tasks_index_path %></h2>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit your task</h1>

  <%= render 'form', task: @task %>

  <hr>
  <%= link_to tasks_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul id="tasks">
  <% @tasks.each do |task|%>
    <li>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task.id) %>
      <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
        <i class="fas fa-trash" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end%>
</ul>
<hr>
<%= link_to new_task_path do %>
    <i class="far fa-plus"></i> Add a new task
<% end %>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Add a new task to your list sir</h1>
    <%= render 'form', task: @task %>
  <hr>
  <%= link_to tasks_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
<%= link_to edit_task_path(@task.id), class: 'pull-right btn btn-default' do %>
  <i class="far fa-pencil"></i> Edit this task
<% end %>
  <h1><%= @task.title %></h1>
  <p class="details"><%= @task.details %><p>

  <% if @task.completed %>
    <i class="fa fa-check-square-o"></i> This task is completed
  <% else %>
    <i class="fa fa-square-o"></i> This task is not completed yet
  <% end %>
  <hr>
  <%= link_to tasks_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>